import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { styled } from 'stitches.config'
import { Table } from '@geist-ui/core'
import { animate, glide } from "motion"
import React, { useEffect } from 'react'
import { BatteryIcon, WifiIcon } from '@iconicicons/react'


const inter = Inter({ subsets: ['latin'] })

const MainBlock = styled("div", {
  height: '100vh',
  width: '100vw',
  backgroundColor: '$mauve1',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  gap: '$4',
})

const Box = styled("div", {
  display: 'flex'
})

const Card = styled("div", {
  display: "flex",
  border: '1px solid $mauveA5',
  padding: "$4",
  borderRadius: '6px',
  backgroundColor: '$mauveA2',
  flexDirection: 'column',
  width: '100%',
  gap: '$2'
})
const CardTitle = styled("h3", {
  fontSize: '$4',
  lineHeight: '130%',
  fontWeight: '500',
  color: '$mauve12',
  margin: 0,
})
const CardDescription = styled("p", {
  margin: 0,
  fontSize: '$3',
  lineHeight: '130%',
  color: '$mauve11',
})

const GlossyCard = styled('div', {
  boxShadow: '0px 0px 1px rgba(0, 0, 0, 0.12), 0px 1px 0px rgba(0, 0, 0, 0.08), 0px 2px 2px rgba(0, 0, 0, 0.06), 0px 3px 3px rgba(0, 0, 0, 0.04), 0px 4px 4px rgba(0, 0, 0, 0.03), inset 0px 0px 0px 1px rgba(0, 0, 0, 0.01);',
  border: '1px solid $mauveA3',
  background: 'linear-gradient(180deg, #FFFFFF 35.22%, #F3F4F6 100%)',
  borderRadius: '6px',
  width: 'fit-content',
  padding: '$3',
  display: 'flex',
  flexDirection: 'column',
  gap: '$3'
})



export default function Home() {

  useEffect(() => {
    animate(
      "#graphics",
      { x: 0, opacity: 1 },
      { easing: glide({ velocity: -100 }) }
    )
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBlock>
        <Box css={{
          maxWidth: '1280px'
        }}>
          <Box css={{
            height: '100%',
            width: '100%',
            justifyContent: 'space-between',
            display: 'flex',
            alignItems: 'center'
          }}
            id="graphics"
          >
            <Box css={{
              borderRadius: '20px',
              flexDirection: 'column',
              gap: '$3',
              padding: '0 $4 $3 $4',
              border: '1px solid $mauve5',
              maxWidth: '320px'
            }}>
              <Box css={{
                gap: '$2',
                width: '100%',
                justifyContent: ' flex-end',
                marginTop: '$1'
              }}>
                <Image src={"5g.svg"} height={20} width={20} alt={'5g icon'}></Image>
                <BatteryIcon width={20} height={20} />
                <WifiIcon width={20} height={20} />
              </Box>
              <Card>
                <CardTitle>
                  Lightning fast look up
                </CardTitle>
                <CardDescription>
                  Guarantee near-instant latency on cache hits.
                </CardDescription>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }}>
                  Try me
                </button>
              </Card>
              <Card>
                <CardTitle>
                  Self-updating cache
                </CardTitle>
                <CardDescription>
                  Don’t worry about stale reads or implementing cache invalidation.
                </CardDescription>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }} >
                  Show me
                </button>
              </Card>
              <Card>
                <CardTitle>
                  Scale your reads
                </CardTitle>
                <CardDescription>
                  Protect your database from traffic and horizontally scale.
                </CardDescription>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }}>
                  Try me
                </button>
              </Card>
            </Box>
            <Box css={{
              flexDirection: 'column',
              gap: '$3'
            }}>
              <GlossyCard css={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center'
              }}>
                <Image src={"Logo.svg"} height={36} width={36} alt={'ReadySet Logo'}></Image>
              </GlossyCard>
              <GlossyCard css={{
              }}>
                <Table data={
                  [
                    {
                      id: '1',
                      author: 'Alana',
                      title: 'Why ReadySet rocks',
                      misc: '...',
                      likes: '621'
                    },
                    {
                      id: '2',
                      author: 'Jay',
                      title: 'ReadySet February release',
                      misc: '...',
                      likes: '509'

                    },
                    {
                      id: '3',
                      author: 'Griffin',
                      title: 'Engineering Blog #1',
                      misc: '...',
                      likes: '801'

                    },
                  ]
                }>
                  <Table.Column prop="id" label="id" />
                  <Table.Column prop="author" label="author" />
                  <Table.Column prop="title" label="title" />
                  <Table.Column prop="likes" label="likes" />

                </Table>
              </GlossyCard>
            </Box>
            <Box css={{
              flexDirection: 'column',
              gap: '$3',
              position: 'relative'

            }}> <GlossyCard css={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center'
            }}>
                <Image src={"database.svg"} height={36} width={36} alt={'Database Icon'}></Image>
              </GlossyCard>
              <GlossyCard css={{
              }}>
                <Table data={
                  [
                    {
                      id: '1',
                      author: 'Alana',
                      title: 'Why ReadySet rocks',
                      misc: '...'
                    },
                    {
                      id: '2',
                      author: 'Jay',
                      title: 'ReadySet February release',
                      misc: '...'
                    },
                    {
                      id: '3',
                      author: 'Griffin',
                      title: 'Engineering Blog #1',
                      misc: '...'
                    },
                  ]
                }>
                  <Table.Column prop="id" label="id" />
                  <Table.Column prop="author" label="author" />
                  <Table.Column prop="title" label="title" />
                </Table>
              </GlossyCard>
              <GlossyCard css={{
                position: 'absolute',
                right: -50,
                bottom: -200,
              }}>
                <Table data={
                  [
                    {
                      story_id: '1',
                      user: 'Griffin',
                      timestamp: '...'
                    },
                    {
                      story_id: '1',
                      user: 'Greg',
                      timestamp: '...'

                    },
                    {
                      story_id: '3',
                      user: 'David',
                      timestamp: '...'

                    },
                  ]
                }>
                  <Table.Column prop="story_id" label="story_id" />
                  <Table.Column prop="user" label="user" />
                  <Table.Column prop="timestamp" label="timestamp" />

                </Table>
              </GlossyCard>
            </Box>
          </Box>
        </Box>
      </MainBlock>
    </>
  )
}
