import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { styled } from 'stitches.config'
import { Table } from '@geist-ui/core'
import { animate, glide } from "motion"
import React, { useEffect } from 'react'
import { BatteryIcon, WifiIcon } from '@iconicicons/react'


const inter = Inter({ subsets: ['latin'] })

const MainBlock = styled("div", {
  height: '100vh',
  width: '100vw',
  backgroundColor: '$mauve1',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  gap: '$4',
})

const Box = styled("div", {
  display: 'flex'
})

const Card = styled("div", {
  display: "flex",
  border: '1px solid $mauveA5',
  padding: "$3",
  borderRadius: '6px',
  backgroundColor: '$mauveA2',
  flexDirection: 'column',
  width: '100%',
  gap: '$2'
})
const CardTitle = styled("h3", {
  fontSize: '$4',
  lineHeight: '130%',
  fontWeight: '500',
  color: '$mauve12',
  margin: 0,
})
const CardDescription = styled("p", {
  margin: 0,
  fontSize: '$3',
  lineHeight: '130%',
  color: '$mauve11',
})

const GlossyCard = styled('div', {
  boxShadow: '0px 0px 1px rgba(0, 0, 0, 0.12), 0px 1px 0px rgba(0, 0, 0, 0.08), 0px 2px 2px rgba(0, 0, 0, 0.06), 0px 3px 3px rgba(0, 0, 0, 0.04), 0px 4px 4px rgba(0, 0, 0, 0.03), inset 0px 0px 0px 1px rgba(0, 0, 0, 0.01);',
  border: '1px solid $mauveA3',
  background: 'linear-gradient(180deg, #FFFFFF 35.22%, #F3F4F6 100%)',
  borderRadius: '6px',
  width: 'fit-content',
  padding: '$3',
  display: 'flex',
  flexDirection: 'column',
  gap: '$3'
})



export default function Home() {

  useEffect(() => {

  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainBlock>
        <Box css={{
          maxWidth: '1280px',
          width: '100%'
        }}>
          <Box css={{
            height: '100%',
            width: '100%',
            justifyContent: 'space-between',
            display: 'flex',
            alignItems: 'center'
          }}
          >
            <Box css={{
              borderRadius: '20px',
              flexDirection: 'column',
              gap: '$3',
              padding: '0 $4 $3 $4',
              border: '1px solid $mauve5',
              minWidth: '320px'
            }}>
              <Box css={{
                gap: '$2',
                width: '100%',
                justifyContent: ' flex-end',
                marginTop: '$1'
              }}>
                <Image src={"5g.svg"} height={20} width={20} alt={'5g icon'}></Image>
                <BatteryIcon width={20} height={20} />
                <WifiIcon width={20} height={20} />
              </Box>
              <Card>
                <div>
                  <CardTitle>
                    Lightning fast look up
                  </CardTitle>
                  <CardDescription>
                    Near-instant latency on cache hits.
                  </CardDescription>
                </div>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }}
                  onClick={() => {
                    animate('#line1',
                      { backgroundColor: ["red", "green", "blue", "yellow", "gray"], height: ['10px', '2px', '6px', '3px', '1px'] }
                      , { easing: "ease-out", duration: 2 },)
                  }}
                >
                  Try me
                </button>
              </Card>
              <Card>
                <div>
                  <CardTitle>
                    Self-updating cache
                  </CardTitle>
                  <CardDescription>
                    Don’t worry about stale reads or implementing cache invalidation.
                  </CardDescription>
                </div>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }} >
                  Show me
                </button>
              </Card>
              <Card>
                <div>
                  <CardTitle>
                    Scale your reads
                  </CardTitle>
                  <CardDescription>
                    Protect your database from traffic and horizontally scale.
                  </CardDescription>
                </div>
                <button style={{
                  width: 'fit-content',
                  marginTop: '16px'
                }}>
                  Try me
                </button>
              </Card>
            </Box>
            <Box css={{
              width: '100%',
              height: '1px',
              backgroundColor: '$mauve8'
            }}
              id='line1' />
            <Box css={{
              flexDirection: 'column',
              gap: '$3',
              minWidth: '250px'

            }}>
              <GlossyCard css={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center'
              }}>
                <Image src={"Logo.svg"} height={36} width={36} alt={'ReadySet Logo'}></Image>
              </GlossyCard>
              <GlossyCard
                id="rtable">
                <Table data={
                  [
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      likes: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      likes: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      likes: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />

                    },
                  ]
                }>
                  <Table.Column prop="id" />
                  <Table.Column prop="author" />
                  <Table.Column prop="title" />
                  <Table.Column prop="likes" />

                </Table>
              </GlossyCard>
            </Box>
            <Box css={{
              width: '100%',
              height: '1px',
              backgroundColor: '$mauve8'
            }} id="line2" />
            <Box css={{
              flexDirection: 'column',
              gap: '$3',
              position: 'relative',
              minWidth: '320px'

            }}> <GlossyCard css={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center'
            }}>
                <Image src={"database.svg"} height={36} width={36} alt={'Database Icon'}></Image>
              </GlossyCard>
              <GlossyCard
                id="table1">
                <Table data={
                  [
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                    {
                      id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      author: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      title: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      misc: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                  ]
                }>
                  <Table.Column prop="id" />
                  <Table.Column prop="author" />
                  <Table.Column prop="title" />
                </Table>
              </GlossyCard>
              <GlossyCard css={{
                position: 'absolute',
                right: -50,
                bottom: -200,
              }}
                id="table2"
              >
                <Table data={
                  [
                    {
                      story_id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      user: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      timestamp: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />
                    },
                    {
                      story_id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      user: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      timestamp: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />

                    },
                    {
                      story_id: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      user: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />,
                      timestamp: <Box css={{ backgroundColor: '$mauve5', width: '40px', height: '20px', borderRadius: '6px' }} />

                    },
                  ]
                }>
                  <Table.Column prop="story_id" />
                  <Table.Column prop="user" />
                  <Table.Column prop="timestamp" />

                </Table>
              </GlossyCard>
            </Box>
          </Box>
        </Box>
      </MainBlock>
    </>
  )
}
